GDP/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from sistema import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^criar_permissoes/', views.criar_permissoes),
    url(r'^login/$', views.login_sistema),
    url(r'^logout/$', views.logout_sistema),
    url(r'^home/$', views.home),   # a ser implementada
    url(r'^cadastra_funcionario/$', views.funcionario_cadastrar),
    url(r'^cadastra_projeto/$', views.projeto_cadastrar),
    url(r'^aloca_pessoa/(?P<id_projeto>[0-9]+)/$', views.pessoa_alocar),
    url(r'^projetos/$', views.projetos_listar),
    url(r'^projetos/(?P<id_projeto>[0-9]+)/$', views.projeto_ver),
    url(r'^projetos/(?P<id_projeto>[0-9]+)/ver_equipe', views.pessoa_alocar),
    url(r'^projetos/(?P<id_projeto>[0-9]+)/modifica_status', views.projeto_status),
    url(r'^projetos/(?P<id_projeto>[0-9]+)/etapa/(?P<id_etapa>[0-9]+)/$', views.documentos_ver),
    url(r'^projetos/(?P<id_projeto>[0-9]+)/etapa_atualiza/(?P<id_etapa>[0-9]+)/$', views.etapa_status),
    url(r'^projetos/(?P<id_projeto>[0-9]+)/etapa/(?P<id_etapa>[0-9]+)/requisita_documento/', views.documento_requisitar),
    url(r'^projetos/(?P<id_projeto>[0-9]+)/etapa/(?P<id_etapa>[0-9]+)/avalia_documento/(?P<id_documento>[0-9]+)/$', views.documento_avaliar),
    url(r'^projetos/(?P<id_projeto>[0-9]+)/etapa/(?P<id_etapa>[0-9]+)/escreve_documento/(?P<id_documento>[0-9]+)/$', views.documento_escrever),
    url(r'^projetos/(?P<id_projeto>[0-9]+)/etapa/(?P<id_etapa>[0-9]+)/avalia_documento/(?P<id_documento>[0-9]+)/aprova_documento/$', views.documento_aprovar),
    url(r'^projetos/(?P<id_projeto>[0-9]+)/etapa/(?P<id_etapa>[0-9]+)/avalia_documento/(?P<id_documento>[0-9]+)/reprova_documento/$', views.documento_reprovar),
]

sistema/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
cargos = (
    ('c', 'Coordenador'),
    ('g', 'Gerente'),
    ('a', 'Analista'),
    ('u', 'Usuário'),
)

niveis_formacao = (
    ('0', "Técnico"),
    ('1', "Superior Incompleto"),
    ('2', "Superior Completo"),
    ('3', "Pós-Graduado"),
    ('4', "Outro"),
)

status_etapa = (
    ('0', "Planejada"),
    ('1', "Em progresso"),
    ('2', "Concluída")
)

status_documento = (
    ('0', "Requisitado"),
    ('1', "A avaliar"),
    ('2', "Aprovado")
)


class Projeto(models.Model):

    nome_projeto = models.CharField("Nome do Projeto ", max_length=128)
    inicio = models.DateField("Data de criação", null = True)
    prazo = models.DateField("Prazo final", null = True)
    status = models.BooleanField("Concluído", default = False, blank = True)
    class Meta:
        verbose_name = "Projeto"
        verbose_name_plural = "Projetos"

    def __unicode__(self):
        return self.nome_projeto

class Contato(models.Model):

    residencial = models.IntegerField("Telefone residencial", null = True)
    comercial = models.IntegerField("Telefone comercial", null = True)
    celular = models.IntegerField("Celular", null = True)
    email = models.EmailField("Email")
    endereco = models.CharField("Endereço", max_length=128, null = True)

    class Meta:
        verbose_name = "Contato"
        verbose_name_plural = "Contatos"

    def __unicode__(self):
        return self.email

class Funcionario(models.Model):

    nome = models.CharField("Nome", max_length=128)
    contato = models.OneToOneField(Contato, null = True) #null não é salvo no BD e blank não é requerido no form
    cargo = models.CharField(max_length=16, choices = cargos)
    nivel_formacao = models.CharField("Nível de formação", max_length=16, choices = niveis_formacao)
    usuario = models.OneToOneField(User, blank = True, null=True)
    projeto = models.ForeignKey(Projeto, blank = True, null = True)

    class Meta:
        verbose_name = "Funcionário"
        verbose_name_plural = "Funcionários"

    def __unicode__(self):
        return self.nome

class Gerente(models.Model):
    """docstring for Gerente"""
    def __init__(self, arg):
        super(Gerente, self).__init__()
        self.arg = arg


class Cliente(models.Model):

    nome = models.CharField("Nome do Cliente", max_length=128)
    contato = models.OneToOneField(Contato)
    projeto = models.OneToOneField(Projeto)

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"

    def __unicode__(self):
        return self.nome


class Etapa(models.Model):

    nome = models.CharField("Nome da Etapa", max_length=128)
    inicio = models.DateField("Data de criação", blank=True, null=True)
    prazo = models.DateField("Prazo Final", blank=True, null=True)
    status = models.CharField(max_length=16, choices = status_etapa)
    projeto = models.ForeignKey(Projeto)

    class Meta:
        verbose_name = "Etapa"
        verbose_name_plural = "Etapas"

    def __unicode__(self):
        return self.nome + ' - ' + self.projeto.nome_projeto

class Documento(models.Model):

    nome = models.CharField("Nome do Documento", max_length=128)
    data_criacao = models.DateField("Data de requisição")
    status = models.CharField(max_length=16, choices = status_documento)
    data_revisao = models.DateField("Última modificação", blank=True, null=True)
    data_aprovacao = models.DateField("Data de avaliação", blank=True, null=True)
    texto = models.TextField("Detalhamento", blank=True, null=True)
    etapa = models.ForeignKey(Etapa)

    class Meta:
        verbose_name = "Documento"
        verbose_name_plural = "Documentos"

    def __unicode__(self):
        return self.nome

sistema/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm, TextInput, Select, PasswordInput, Textarea, CharField
from django import forms
from sistema.models import *
from localflavor.br.forms import *

# Register your forms here.

class LoginForm(forms.Form):
    username = forms.CharField(max_length=64)
    password = forms.CharField(max_length=64, widget=forms.PasswordInput)

class FuncionarioForm(forms.ModelForm):
    class Meta:
        model = Funcionario
        exclude = ('contato','usuario', 'projeto','cargo',)

class ContatoForm(forms.ModelForm):
    class Meta:
        model = Contato
        fields = '__all__'

class ProjetoForm(forms.ModelForm):
    class Meta:
        model = Projeto
        exclude = ('status',)

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        exclude = ('projeto', 'contato',)

class AlocarForm(forms.Form):
    gerente = forms.ModelChoiceField(queryset=Funcionario.objects.all().order_by('nome'))
    analista1 = forms.ModelChoiceField(queryset=Funcionario.objects.all().order_by('nome'))
    analista2 = forms.ModelChoiceField(queryset=Funcionario.objects.all().order_by('nome'))
    analista3 = forms.ModelChoiceField(queryset=Funcionario.objects.all().order_by('nome'))
    analista4 = forms.ModelChoiceField(queryset=Funcionario.objects.all().order_by('nome'))

class DocumentoForm(forms.ModelForm):
    class Meta:
        model = Documento
        fields = ('nome',)

class EscreverForm(forms.ModelForm):
    class Meta:
        model = Documento
        fields = ('texto',)

class ProjetoStatusForm(forms.ModelForm):
    class Meta:
        model = Projeto
        fields = '__all__'

class EtapaForm(forms.ModelForm):
    class Meta:
        model = Etapa
        exclude = ('projeto',)

sistema/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from sistema.forms import *
from django.contrib.auth.decorators import login_required, permission_required
# Create your views here.
from datetime import date
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

# def criar_permissoes(request):
#     grupo_a = Group(name='administrador')
#     somemodel_ct = ContentType.objects.get(app_label='auth', model='user')
#     perm_g = Permission(name='Permissao gerente', codename='perm_g',content_type=somemodel_ct)
#     perm_c = Permission(name='Permissao coordenador', codename='perm_c',content_type=somemodel_ct)
#     g1 = Group(name='analista')
#     g2 = Group(name='gerente')
#     g3 = Group(name='coordenador')
#     lista = Funcionario.objects.all()
#     for u in lista:
#         if u.cargo == 'a':
#             u.group = [g1]
#         elif u.cargo == 'g':
#             u.group = [g2]
#         elif u.cargo == 'c':
#             u.group = [g3]
#         if u.usuario.is_superuser()==True:
#             u.group = [g1,g2,g3]
#     return redirect("/admin/")

def login_sistema (request):
    if request.method=="GET":
        login_form=LoginForm()
    else:
        login_form=LoginForm(request.POST)
        if login_form.is_valid():
            usuario = login_form.cleaned_data['username']
            senha = login_form.cleaned_data['password']
            user = authenticate(username=usuario, password=senha)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect("/home/")
                else:
                    messages.error(request, 'Este usuário não está ativo')
            else:
                messages.error(request, 'Este usuário e/ou senha não existe')
        else:
            messages.error(request, 'Confira o preenchimento dos campos abaixo')

    return render (request, "login.html",locals())

@login_required
def logout_sistema (request):
    logout(request)
    return redirect('/login/')

@login_required
def home(request):
    # if funcionario.usuario.senha == funcionario.email:
    #     alerta =
    usuario = request.user
    funcionario_corrente = Funcionario.objects.get(usuario=usuario)
    try:
        nfunc = Funcionario.objects.count()
    except:
        nfunc = 0
    try:
        nproj = Projeto.objects.count()
    except:
        nproj = 0
    c = funcionario_corrente.cargo
    if c == 'g' or c == 'a':
        projeto = funcionario_corrente.projeto
        lista_etapas = Etapa.objects.filter(projeto = projeto)
        for e in lista_etapas:
            lista_doc = Documento.objects.filter(etapa = e)
            for d in lista_doc:
                if d.status =='1' and c =='g':
                    messages.warning(request, 'Você tem documento(s) a ser(em) avaliado(s)')
                    c = '0'
                elif d.status =='0' and c =='a':
                    messages.warning(request, 'Você tem documento(s) requisitado(s)')
                    c = '0'
    return render (request, "inicio.html",locals())


# cadastro do funcionario, sendo o usuario e senha igual ao email
@login_required
@permission_required('auth.perm_c', login_url='/home/')
def funcionario_cadastrar(request):
    funcionario_corrente = Funcionario.objects.get(usuario=request.user)
    funcionario_form = FuncionarioForm()
    contato_form = ContatoForm()
    if request.method == 'POST':
        funcionario_form = FuncionarioForm(request.POST)
        contato_form = ContatoForm(request.POST)
        if funcionario_form.is_valid() and contato_form.is_valid():
            email = contato_form.cleaned_data['email']
            try:
                usuario_existente = User.objects.get(email = email)
                messages.error(request, 'Este email já foi cadastrado')
            except:
                contato = contato_form.save()
                user = User.objects.create_user(username=email,email=email,password=email)
                user.save()
                funcionario = funcionario_form.save(commit = False)
                funcionario.usuario = user
                funcionario.contato = contato
                funcionario.cargo = 'u'
                funcionario.save()
                messages.success(request, 'Funcionário criado com sucesso!')
        else:
            messages.error(request, 'Confira o preenchimento dos dados')
    return render (request, "funcionario_cadastrar.html", locals())

@login_required
@permission_required('auth.perm_c', login_url='/home/')
def projeto_cadastrar(request):
    funcionario_corrente = Funcionario.objects.get(usuario=request.user)
    projeto_form = ProjetoForm()
    cliente_form = ClienteForm()
    contato_form = ContatoForm()
    if request.method == 'POST':
        projeto_form = ProjetoForm(request.POST)
        cliente_form = ClienteForm(request.POST)
        contato_form = ContatoForm(request.POST)
        if projeto_form.is_valid() and cliente_form.is_valid():
            projeto = projeto_form.save()
            criar_etapas(projeto.id)
            contato = contato_form.save()
            cliente = cliente_form.save(commit=False)
            cliente.projeto = projeto
            cliente.contato = contato
            cliente.save()
            messages.success(request, 'Projeto cadastrado com sucesso!')
            return redirect('/aloca_pessoa/%d/' % projeto.id)
        else:
            messages.error(request, 'Confira o preenchimento dos dados')
    return render (request, "projeto_cadastrar.html", locals())

def criar_etapas(id_projeto):
    projeto_corrente = Projeto.objects.get(id=id_projeto)
    etapa1 = Etapa.objects.create(nome="Modelo de Negócios",projeto=projeto_corrente)
    etapa2 = Etapa.objects.create(nome="Requisitos",projeto=projeto_corrente)
    etapa3 = Etapa.objects.create(nome="Análise e Design",projeto=projeto_corrente)
    etapa4 = Etapa.objects.create(nome="Implementação",projeto=projeto_corrente)
    etapa5 = Etapa.objects.create(nome="Teste",projeto=projeto_corrente)
    etapa6 = Etapa.objects.create(nome="Desenvolvimento",projeto=projeto_corrente)
    return

@login_required
def pessoa_alocar(request, id_projeto):
    usuario = request.user
    funcionario_corrente = Funcionario.objects.get(usuario=usuario)
    cargo = funcionario_corrente.cargo
    projeto_corrente = Projeto.objects.get(id=id_projeto)
    equipe_atual = Funcionario.objects.filter(projeto=projeto_corrente)
    alocar_form = AlocarForm()
    if request.method == 'POST':
        alocar_form = AlocarForm(request.POST)
        if alocar_form.is_valid():
            limpa_equipe_atual(projeto_corrente.id)
            gerente = alocar_form.cleaned_data['gerente']
            gerente.projeto = projeto_corrente
            gerente.cargo = 'g'
            g1 = Group.objects.get(name='gerente')
            g1.user_set.add(gerente.usuario)
            analista1 = alocar_form.cleaned_data['analista1']
            analista1.projeto = projeto_corrente
            analista1.cargo = 'a'
            g2 = Group.objects.get(name='analista')
            g2.user_set.add(analista1.usuario)
            analista2 = alocar_form.cleaned_data['analista2']
            analista2.projeto = projeto_corrente
            analista2.cargo = 'a'
            g2.user_set.add(analista2.usuario)
            analista3 = alocar_form.cleaned_data['analista3']
            analista3.projeto = projeto_corrente
            analista3.cargo = 'a'
            g2.user_set.add(analista3.usuario)
            analista4 = alocar_form.cleaned_data['analista4']
            analista4.projeto = projeto_corrente
            analista4.cargo = 'a'
            g2.user_set.add(analista4.usuario)
            gerente.save()
            analista1.save()
            analista2.save()
            analista3.save()
            analista4.save()
            messages.success(request, "Pessoal alocado com sucesso!")
        else:
            messages.error(request, "Erro no envio de dados")
    return render(request, "pessoa_alocar.html", locals())

def limpa_equipe_atual(id_projeto):
    projeto_corrente = Projeto.objects.get(id=id_projeto)
    lista = Funcionario.objects.filter(projeto=projeto_corrente)
    g1 = Group.objects.get(name='gerente')
    g2 = Group.objects.get(name='analista')
    print("oi")
    for f in lista:
        print("nn")

        f.cargo = 'u'
        f.projeto = None
        u = f.usuario
        try:
            g1.user_set.remove(u)
        except:
            g2.user_set.remove(u)
        f.save()
    return

@login_required
# @permission_required('auth.perm_a', login_url='/home/')
def projetos_listar(request):
    usuario = request.user
    funcionario_corrente = Funcionario.objects.get(usuario=usuario)
    cargo = funcionario_corrente.cargo
    if cargo == 'g' or cargo == 'a':
        lista=[]
        lista.append(funcionario_corrente.projeto)
    else:
        lista = Projeto.objects.all()
    lista = Projeto.objects.all()
    # for p in lista:
    #     etapas = Etapa.objects.filter(projeto = p)
    #     p.status = True
    #     for e in etapas:
    #         if e.status != '2':
    #             p.status = False
    #             break
    #     p.save()
    return render(request, "projetos.html", locals())

@login_required
@permission_required('auth.perm_g', login_url='/home/')
def projeto_status(request, id_projeto):
    funcionario_corrente = Funcionario.objects.get(usuario=request.user)
    projeto_corrente = Projeto.objects.get(id = id_projeto)
    projeto_form = ProjetoStatusForm(instance=projeto_corrente)
    if request.method == 'POST':
        projeto_form = ProjetoStatusForm(request.POST)
        if projeto_form.is_valid():
            p = projeto_form.save(commit=False)
            projeto_corrente.inicio = p.inicio

sistema/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>GDP - {% block title %}{% endblock title %}</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width">

	<!-- ===================== TOUCH ICONS ===================== -->
	<link rel="shortcut icon" href="/static/favicon.png">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/apple-touch-icon-144-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/apple-touch-icon-114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/apple-touch-icon-72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="/static/apple-touch-icon-57-precomposed.png">

	<!-- ===================== MASTER CSS ===================== -->
	<link rel="stylesheet" type="text/css" href="/static/css/jasny-bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">

	<!-- ===================== ICONS CSS ===================== -->
	<link rel="stylesheet" type="text/css" href="/static/css/icon/fugue.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/icon/elusive.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/icon/font-awesome.min.css">

	<!-- ===================== SITE CSS ===================== -->
	<link rel="stylesheet" type="text/css" href="/static/css/default.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/default.responsive.min.css">

	<!-- ===================== PLUGINS CSS ===================== -->
	<link rel="stylesheet" type="text/css" href="/static/css/plugins/uniform.default.css">

	<!-- ===================== JQUERY UI CSS ===================== -->
	<link rel="stylesheet" type="text/css" href="/static/css/jui/jquery.ui.min.css">

	<!-- Vendors -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script src="/static/js/vendors/jquery-ui-1.9.2.min.js"></script>


	<script src="/static/js/vendors/modernizr-2.6.2.min.js"></script>

	{% block extrahead %}
	{% endblock extrahead %}


    </head>
    <body class="body5">
        <!--[if lt IE 7]>
            <p class="chromeframe">Você está usando um navegador <strong>ultrapassado</strong>. Por favor <a href="http://browsehappy.com/">atualize seu navegador</a> ou <a href="http://www.google.com/chromeframe/?redirect=true">ative o Google Chrome Frame</a> para melhorar a sua experiência.</p>
        <![endif]-->

        <div id="wrapper" class="boxed">
            <div id="wrapper-inner" class="pattern8">

                <!-- Start Main Header -->
                <div id="main-header">
		    <div class="container-fluid">
			<div class="row-fluid">
			    <div class="span12">
				<div class="title">
				    <h1>GDP <small>v0.4</small></h1>
			        </div>
                                <!-- Start Messages Panel -->
				<div style="position: absolute; left: 330px; top: 9px;">
				{% block mensagens %}
				    {% if messages %}
					{% for message in messages %}
					<div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					<strong>Mensagem do Sistema:</strong> {{ message|safe }}
					</div>
					{% endfor %}
				    {% endif %}
				{% endblock mensagens %}
				</div>
                                <!-- Start Header Panel -->
				<div class="header-panel">
				    <div id="dropdown-patterns" class="dropdown" rel="tooltip" data-placement="bottom" title="Logout">
					<a href="/logout/" class="menu dropdown-toggle" onclick="return confirm('Deseja realmente fazer logout do sistema?')" ><i class="icon iconfa-off"></i></a>
				    </div>
				    <a href="#" class="menu" id="menu-phone" data-menu="mobile"><i class="icon iconfa-tasks"></i></a>
				</div>
                                <!-- End Header Panel -->
			    </div>
			</div>
		    </div>
                </div>
                <!-- End Main Header -->

                <!-- Start Sidebar -->
                <div id="sidebar">

                    <!-- Start Profile Panel -->
                    <div class="profile" data-detach="profile">
                        <div class="profile-pic">
			    <div class="btn-group">

				    <img src="/static/img/avatar/40x40/avatar4.png" width="40px" height="40px" alt="{{membro_logado.user.get_full_name}}" class="dropdown-toggle" data-toggle="dropdown">
                </div>

                        </div>


                        <div class="profile-info">
                            <span class="name">{{funcionario_corrente.nome}}</span>
                            <span class="job">{{funcionario_corrente.get_cargo_display}}</span>
                        </div>


                        <div class="profile-panel">
                            <!-- Start Messages -->
                            <div class="profile-panel-menu" id="panel-message">
                                <a href="/home/" class="menu">
                                    <i class="icon icon-home"></i>
                                    <span class="text">Painel Inicial</span>
                                </a>
                            </div><!-- End Messages -->

                            <!-- Start Notification -->
                            <div class="profile-panel-menu" id="panel-notification">
                                <a href="/admin/" class="menu">
                                    <i class="icon icon-user"></i>
                                    <span class="text">Administrador</span>
                                </a>
                            </div><!-- End Notification -->
                        </div>
                    </div><!-- End Profile Panel -->

                    <!-- Start Main Menu -->
                    <ul class="nav-mainmenu" id="nav-mainmenu">

                        <!-- Start MEMBROS Menu -->
                        <li class="accordion-group">
                            <a href="/cadastra_funcionario/"><span class="icon iconfa-group"></span><span class="text">Funcionários</span><span class="badge pull-right">4</span></a>
                        </li>
                        <!-- End MEMBROS Menu -->

                        <!-- Start PROJETOS Menu -->
                        <li class="accordion-group">
                            <a href="/cadastra_projeto/"><span class="icon iconfa-paste"></span><span class="text">Projetos</span><span class="badge pull-right">5</span></a>
                        </li>
                        <!-- End PROJETOS Menu -->

			<!-- Start EQUIPES Menu -->

                        <li class="accordion-group">
                            <a href="/projetos/"><span class="icon iconfa-folder-open"></span><span class="text">Ver Projetos</span><span class="badge pull-right">3</span></a>
                        </li>
                        <!-- End CONHECIMENTO Menu -->

                    </ul><!-- End Main Menu -->

                </div><!-- End Sidebar -->

                <!-- Start Main Content -->
                <div id="main-content">
                    <p>&nbsp;</p>

                    <h3>{% block titulo %}{% endblock titulo %} <small>{% block subtitulo %}{% endblock subtitulo %}</small></h3>

                    <hr class="style1">

                    <!-- Start Main Content -->
		    <div class="row-fluid" >
			<div class="span12">

			{% block conteudo %}{% endblock conteudo %}
					    </div> <!-- span 12 -->
                    </div><!-- End -->
					<br/>
                </div><!-- End Main Content -->

            </div>
        </div>


        <!-- Flot Plugins -->

	<!-- Site -->
    <script src="/static/js/bootstrap.min.js"></script>
	<script src="/static/js/jasny-bootstrap.min.js"></script>
	<script src="/static/js/plugins/jquery.placeholder.min.js"></script>
	<script src="/static/js/application.js"></script>

        <!-- Plugins -->

	{% block footertag %}
	{% endblock footertag %}
    </body>
</html>

sistema/templates/documento_avaliar.html
{% extends "base.html" %}

{% block title %}Alocar pessoal{% endblock title %}

{% block extrahead %}
{% endblock extrahead %}

{% block titulo %}{{projeto_corrente.nome_projeto}}{% endblock titulo %}

{% block subtitulo %}{{etapa_corrente.nome}}{% endblock subtitulo %}

{% block conteudo %}

<p>{{documento_corrente.texto}}</p>

<a href="{{request.path}}aprova_documento" class="btn">Aprovar</a>
<a href="{{request.path}}reprova_documento" class="btn">Reprovar</a>

{% endblock conteudo %}

{% block footertag %}
{% endblock footertag %}

sistema/templates/documentos.html
{% extends "base.html" %}

{% block title %}Alocar pessoal{% endblock title %}

{% block extrahead %}
{% endblock extrahead %}

{% block titulo %}{{projeto_corrente.nome_projeto}}{% endblock titulo %}

{% block subtitulo %}{{etapa_corrente.nome}}{% endblock subtitulo %}

{% block conteudo %}

{% if lista %}
<table class="table table-hover" id="table2">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Data de Requisição</th>
            <th>Status</th>
            <th>Última modificação</th>
            <th>Data de Avaliação</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for documento in lista%}
        <tr class="odd gradeX">
            <td>{{documento.nome}}</td>
            <td>{{documento.inicio}}</td>
            <td>{{documento.get_status_display}}</td>
            <td>{{documento.data_revisao}}</td>
            <td>{{documento.data_aprovacao}}</td>
            <td><div class="tr-action">
                <div class="tr-action-inner">
                <div class="btn-group">
                <a href="escreve_documento/{{documento.id}}" class="btn"><i class="icon icon-pencil"></i></a>
                <a href="avalia_documento/{{documento.id}}" class="btn"><i class="icon icon-eye-open"></i></a>
                </div>
                </div>
                </div>
            </td>
        </tr>
        {% endfor%}
    </tbody>
</table>
<br>
{% endif %}

<form method="POST" action="requisita_documento/">{% csrf_token %}
    {{documento_form.as_table}}
    <button class="btn" type="submit">Requisitar Documento</button>
    <div class="clearfix"></div>
</form>
{% endblock conteudo %}

{% block footertag %}
{% endblock footertag %}